# Set Site Details
site_name: "Open Source Merb"
site_url: "http://www.opensourcemerb.com"
blog_url: "http://blog.opensourcemerb.com"
admin_email_name: "OpenSourceMerb"
admin_email_address: "opensourcemerb@gmail.com"
version: "v2.0"

# Options
ajax_paging: true
show_social_media: true
require_email_activation: true

# About Page
site_description: "Open Source Merb is a community site dedicated to tracking the best open source Merb web applications."

# SEO Stuff
default_meta_keywords: "open source merb ruby"
default_meta_description: "Open Source Merb is a community site dedicated to tracking the best open source Merb applications."

# Tell a Friend
tellafriend_subject: "Check out OpenSourceMerb.com"
tellafriend_body_intro: "OpenSourceMerb.com is a gallery of the latest and greatest open source Merb projects. Check it out: http://www.opensourcemerb.com"
tellafriend_body_message: "It features an easy to use browse gallery with screenshots plus community driven comments, ratings, and bookmarking."

# Paging Sizes
project_list_max: 25
projects_per_page: 6
bookmarks_per_page: 8

# Set Avatar Sizes
screenshot_sizes: 
  medium: "225x225#"
  thumb: "70x70#"

# Set default avatar
screenshot_default: "/images/default_screenshots/:style.png"

# Retarded Spam Question
spam_question: What is 3 plus 2?
spam_answer: 
  - "5"
  - "five"